os:
  - osx
  - linux
language: generic
matrix:
  include:
    - os: osx
      osx_image: xcode9
    - os: linux
      dist: trusty
      sudo: required
      env:
        - SWIFT_VERSION=swift-4.0-DEVELOPMENT-SNAPSHOT-2017-09-08-a
script:
  - ./scripts/build
notifications:
  email:
    on_success: never
    on_failure: change
